export const SOCKET_JOIN = "join"
export const SOCKET_JOIN_ROOM = "join room"
export const SOCKET_MESSAGE = "message"
export const SOCKET_MESSAGE_RECEIVED = "message received"
export const SOCKET_TYPING = "typing"
export const SOCKET_USER_TYPING = "user typing"
